### PR TITLE
display errors instead of piping them to /dev/null

### PR DESCRIPTION
**Pull request by irgendwr**
note: untested

### CODE REVIEW

**Comment by mxschmitt** [comment]
Please test by using e.g. an not existing command / incorrect parameter, thanks!

**Comment by DAThosting** [comment]
Have to change it for curl, cause the download progressbar is shown...

**Comment by irgendwr** [comment]
feel free to edit this branch

**Comment by DAThosting** [comment]
Doesn't work for checking the http status.
(In my case)

**Pull request merged**
