### PR TITLE
fix: Installer problems on Ubuntu

### LINKED ISSUE #81: Failed to start chronyd.service: Unit chronyd.service not found.
image

There us an error in the skript:

This is the fix:
apt install chrony 

pls add it to the skript

### LINKED ISSUE #82: Ubuntu 20.04 needs elseif because python is now phyton 3
```bash

# Install necessary aptitudes for sinusbot.

magentaMessage "Installing necessary packages. Please wait..."

if [[ -f /etc/centos-release ]]; then
  yum -y -q install screen xvfb libxcursor1 ca-certificates bzip2 psmisc libglib2.0-0 less cron-apt ntp python iproute which dbus libnss3 libegl1-mesa x11-xkb-utils libasound2 libxcomposite-dev libxi6 libpci3 libxslt1.1 libxkbcommon0 libxss1 >/dev/null
  update-ca-trust extract >/dev/null
else
  # Detect if systemctl is available then use systemd as start script. Otherwise use init.d
  if [ "$OSRELEASE" == "18.04" ] && [ "$OS" == "ubuntu" ]; then
    apt-get -y install chrony
  else
    apt-get -y install ntp
  fi
  apt-get -y -qq install libfontconfig libxtst6 screen xvfb libxcursor1 ca-certificates bzip2 psmisc libglib2.0-0 less cron-apt **python** iproute2 dbus libnss3 libegl1-mesa x11-xkb-utils libasound2 libxcomposite-dev libxi6 libpci3 libxslt1.1 libxkbcommon0 libxss1
  update-ca-certificates >/dev/null
fi
...
```
must be named as phyton3 in Ubuntu 20.04 Focal fassa. By applying this change sinunsbot works like a charm again.

### LINKED ISSUE #91: Failed to set ntp: NTP not supported
Trigger für man-db (2.9.4-2) werden verarbeitet ...
Trigger für dbus (1.12.20-2) werden verarbeitet ...
Packages installed!
Failed to set ntp: NTP not supported
Command which failed was: "      timedatectl set-ntp yes". Please try to execute it manually and attach the output to the bug report in the forum thread.

Executing the command manually also results in "Failed to set ntp: NTP not supported".
(Debian 11 latest version)

### LINKED ISSUE #97: Installer on Ubuntu 22 not working
Added the testing matrix in https://github.com/SinusBot/installer-linux/pull/96 so we see the failure.

Most likely related to:

- https://github.com/SinusBot/installer-linux/issues/91
- #82 
- #81

cc @Lulalaby

### PR DESCRIPTION
**Pull request by Lulalaby**
chore: Update readme
devops: Add discord test
chore: remove time operations and private use

closes: #97
closes: #91 
closes: #82
closes: #81

Discord-DiscordCanary-2022-10-05 12h56_51_01

### CODE REVIEW

**Comment by Lulalaby** [comment]
@mxschmitt @flyth

**Comment by Lulalaby** [comment]
For the discord token write me please

**Comment by Lulalaby** [comment]
So this is now ready
Added additionally despawning to not flood sinusbots teamspeak server

**Comment by mxschmitt** [comment]
This change is not reviewable since it contains too many changes which don't belong together. Can you split it up into different PRs?

**Comment by Lulalaby** [comment]
> This change is not reviewable since it contains too many changes which don't belong together. Can you split it up into different PRs?

It's hard for me to split that now :/ 
My head is hurting haha
I've let the [shell-format](https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format) extension run, which probably made this kinda unreadable.

I would be happy if you could review it anyways somehow

**Pull request closed without merging**
